### ISSUE TITLE
Source code location?

### ISSUE THREAD

**Issue by Fmstrat** [Kareadita/tachiyomi-extensions#4]
As this is a non Play Store vetted app, where is the source? I was looking at an OPDS item for Mihon but this repo only contains an APK for the extension. Thanks!

**Comment by ThePromidius** [comment]
The repo was moved to an orphan repo. I just kind of forgot to make it public and left this one for backwards compatibility (links and stuff)

**Comment by Fmstrat** [comment]
Ahhh that makes sense. Which orphan repo and are you maintaining a new one somewhere?

**Comment by ThePromidius** [comment]
it's under https://github.com/Kareadita/tach-extension but i can't make it public. Maybe @majora2007 can

**Comment by Fmstrat** [comment]
> it's under https://github.com/Kareadita/tach-extension but i can't make it public. Maybe @majora2007 can

Ahh, ok! Will wait to hear from @majora2007 . Thanks again!

**Comment by majora2007** [comment]
I made it public
